"""Add real_name and organization to User

Revision ID: 2bd45df0fe71
Revises: 87996e8e4252
Create Date: 2026-02-07 00:06:50.849137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd45df0fe71'
down_revision = '87996e8e4252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # Add columns as nullable first
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('real_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('organization', sa.String(length=200), nullable=True))

    # Set default values for existing users
    op.execute("UPDATE users SET real_name = username WHERE real_name IS NULL")
    op.execute("UPDATE users SET organization = '' WHERE organization IS NULL")

    # Now set NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('real_name', existing_type=sa.String(length=100), nullable=False)
        batch_op.alter_column('organization', existing_type=sa.String(length=200), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('organization')
        batch_op.drop_column('real_name')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
