"""Add manual review fields to TestResult

Revision ID: 4f29765e6920
Revises: ab0859932264
Create Date: 2026-02-06 13:52:52.636482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f29765e6920'
down_revision = 'ab0859932264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_review_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('manual_reviewed_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('manual_review_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('manual_review_comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.drop_column('manual_review_comment')
        batch_op.drop_column('manual_review_time')
        batch_op.drop_column('manual_reviewed_by')
        batch_op.drop_column('manual_review_status')

    # ### end Alembic commands ###
