"""Add User and ReviewerApplication models, add user_id to Question

Revision ID: 87996e8e4252
Revises: 4f29765e6920
Create Date: 2026-02-06 15:46:26.681834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87996e8e4252'
down_revision = '4f29765e6920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Users and reviewer_applications tables already exist, only add user_id to questions
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_questions_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_questions_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
